// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuocignqjaapotmzogkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1b2NpZ25xamFhcG90bXpvZ2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzE2MTgsImV4cCI6MjA3MjkwNzYxOH0.PyjHPRVuOOhiM4sbVdR2rof3HBDXn6b8CC3kEszd1As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});